package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteIPXE writes a lab iPXE script that chainloads local kernel/initramfs
// served from the same HTTP root as the script (see lab/pxe/README.md).
func WriteIPXE(outDir, arch, version, httpBase string) (string, error) {
	kernel, err := assetFileName(AssetKernel, arch)
	if err != nil {
		return "", err
	}
	initramfs, err := assetFileName(AssetInitramfs, arch)
	if err != nil {
		return "", err
	}
	base := strings.TrimRight(httpBase, "/")
	body := fmt.Sprintf(`#!ipxe
# Generated by tools/talos-installer for Talos %s (%s)
# Serve outDir over HTTP and point DHCP/iPXE here (lab/pxe/README.md).
# Alternative: use https://factory.talos.dev PXE URLs for Image Factory schemes.

set base %s
kernel ${base}/%s talos.platform=metal console=tty0 console=ttyS0
initrd ${base}/%s
boot
`, version, arch, base, kernel, initramfs)

	path := filepath.Join(outDir, "boot.ipxe")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", err
	}
	return path, nil
}
