#!/usr/bin/env bash
# Export bare-metal Pulumi machineConfigs (and inventory hints) for USB / talosctl apply.
# Intended after: ./scripts/up.sh primary  (dry_run true or false — configs exist either way)
#
# Usage: ./scripts/export-baremetal-machine-configs.sh
# Env:   PULUMI_STACK (default: dev)
#        OUT_DIR (default: .secrets/bare-metal-configs)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=scripts/lib.sh
source "${ROOT}/scripts/lib.sh"
STACK="${PULUMI_STACK:-dev}"
OUT_DIR="${OUT_DIR:-${ROOT}/.secrets/bare-metal-configs}"
DIR="infra/bare-metal"

need pulumi "Install: https://www.pulumi.com/docs/install/"
need python3 "Need python3 to unpack machineConfigs JSON."

stack_out() {
  local args=("$@")
  (
    cd "${ROOT}/${DIR}"
    pulumi stack output "${args[@]}" 2>/dev/null || true
  )
}

provisioner="$(yaml_section_key primary provisioner | tr -d '[:space:]')"
if [[ "${provisioner}" != "bare-metal" ]]; then
  echo "primary.provisioner is ${provisioner:-unset} — export only applies to bare-metal" >&2
  echo "  Switch config/clusters.yaml or use Azure metal-sim (configs come from VMs)." >&2
  exit 1
fi

echo "==> reading machineConfigs from ${DIR} (stack=${STACK})"
if ! (
  cd "${ROOT}/${DIR}"
  pulumi stack select "${STACK}" >/dev/null 2>&1
); then
  echo "Pulumi stack ${STACK} not found in ${DIR}." >&2
  echo "  Run ./scripts/up.sh primary first (dry_run ok) — that syncs inventory and creates the stack." >&2
  exit 1
fi

RAW="$(stack_out machineConfigs --json --show-secrets)"
if [[ -z "${RAW}" || "${RAW}" == "null" ]]; then
  echo "machineConfigs missing — run ./scripts/up.sh primary first (dry_run ok)." >&2
  exit 1
fi

# baremetal:nodes JSON — same order as machineConfigs keys (role-index).
NODES_JSON="$(
  cd "${ROOT}/${DIR}"
  pulumi config get baremetal:nodes 2>/dev/null || true
)"

mkdir -p "${OUT_DIR}"
find "${OUT_DIR}" -maxdepth 1 -type f \( -name '*.yaml' -o -name 'INVENTORY.txt' -o -name 'APPLY.md' \) -delete

printf '%s' "${RAW}" | python3 -c '
import json, sys, pathlib
out = pathlib.Path(sys.argv[1])
try:
    data = json.load(sys.stdin)
except json.JSONDecodeError as e:
    print(f"machineConfigs is not JSON: {e}", file=sys.stderr)
    sys.exit(1)
if not isinstance(data, dict) or not data:
    print("machineConfigs empty or not an object", file=sys.stderr)
    sys.exit(1)
for name, body in sorted(data.items()):
    if not isinstance(body, str) or not body.strip():
        print(f"skip {name}: empty", file=sys.stderr)
        continue
    path = out / f"{name}.yaml"
    path.write_text(body if body.endswith("\n") else body + "\n", encoding="utf-8")
    print(f"  wrote {path}")
' "${OUT_DIR}"

{
  echo "# Generated by export-baremetal-machine-configs.sh — do not commit"
  echo "clusterEndpoint=$(stack_out clusterEndpoint)"
  echo "apiEndpointIP=$(stack_out apiLoadBalancerIP)"
  echo "ingressIP=$(stack_out ingressIP)"
  echo "installDisk=$(stack_out installDisk)"
  echo "dryRun=$(stack_out dryRun)"
  echo "# file → IP (keys match machineConfigs / primary.nodes inventory index)"
  if [[ -n "${NODES_JSON}" && "${NODES_JSON}" != "null" ]]; then
    printf '%s' "${NODES_JSON}" | python3 -c '
import json, sys
nodes = json.load(sys.stdin)
if not isinstance(nodes, list):
    sys.exit(0)
for i, n in enumerate(nodes):
    if not isinstance(n, dict):
        continue
    role = str(n.get("role", "")).strip()
    ip = str(n.get("ip", "")).strip()
    if role and ip:
        print(f"{role}-{i}={ip}")
'
  else
    echo "# (baremetal:nodes missing — falling back to role IP lists)"
    echo "controlPlaneIPs=$(stack_out controlPlaneIPs --json)"
    echo "workerIPs=$(stack_out workerIPs --json)"
  fi
} >"${OUT_DIR}/INVENTORY.txt"

cat >"${OUT_DIR}/APPLY.md" <<'EOF'
# Apply machine configs (maintenance mode)

Fetch/flash an installer with `./scripts/fetch-talos-installer.sh` (or lab PXE —
see `docs/INSTALL-TALOS.md`). Nodes must reach Talos **maintenance mode**
(apid on :50000) before apply. BMC/Redfish is not automated in OSS.

## Map files → nodes

`INVENTORY.txt` lists `controlplane-N=<ip>` / `worker-N=<ip>` using the **same
inventory index** as Pulumi `machineConfigs` keys (role + index in
`primary.nodes`, not a per-role counter).

Example: if `nodes[0]` is CP and `nodes[1]` is worker, files are
`controlplane-0.yaml` and `worker-1.yaml`.

## Option A — let Pulumi apply (recommended)

After every node is in maintenance mode:

1. Set `dry_run: false` in `config/clusters.yaml`
2. `./scripts/sync-baremetal-config.sh && ./scripts/up.sh primary`
3. Export kubeconfig:
   `pulumi -C infra/bare-metal stack output kubeconfig --show-secrets > .secrets/primary.kubeconfig`

## Option B — manual `talosctl` (USB / air-gap)

```bash
# First apply is insecure (no client certs yet):
talosctl apply-config --insecure --nodes <IP> --file controlplane-0.yaml
talosctl apply-config --insecure --nodes <IP> --file worker-1.yaml
# Then either bootstrap with talosctl, or set dry_run: false and let Pulumi
# ConfigurationApply + Bootstrap finish (idempotent enough for lab use).
```

Do **not** commit this directory (`.secrets/` is gitignored).
EOF

echo "==> exported to ${OUT_DIR}"
ls -la "${OUT_DIR}"
echo
echo "Next: boot Talos to maintenance mode, then either:"
echo "  A) set dry_run: false → ./scripts/up.sh primary"
echo "  B) talosctl apply-config --insecure … (see ${OUT_DIR}/APPLY.md)"
echo "Docs: docs/METAL-PRIMARY.md · docs/INSTALL-TALOS.md"
